name: AI Test Workflow

on:
  push:
    branches:
      - ai-workspace

jobs:
  dry-run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run dry-run test
        run: PYTHONPATH=. python3 tests/test_dry_run_engine.py
